export const HeaderLink = [
  {
    title: "トップ",
    label: "TOP",
    icon: "",
    href: "/",
    show: true,
  },
  {
    title: "サービス",
    label: "SERVICE",
    icon: "",
    href: "/",
    show: true,
  },
  {
    title: "製作の流れ",
    label: "WORK FLOW",
    icon: "",
    href: "/",
    show: true,
  },
  // {
  //   title: "料金紹介",
  //   label: "PRICE",
  //   icon: "",
  //   href: "/",
  //   show: true,
  // },
  {
    title: "よくある質問",
    label: "FAQ",
    icon: "",
    href: "/",
    show: true,
  },
  {
    title: "プロジェクト",
    label: "PROJECTS",
    icon: "",
    href: "/",
    show: true,
  },
  // {
  //   title: "プロフィール",
  //   label: "PROFILE",
  //   icon: "",
  //   href: "/",
  //   show: true,
  // },
  {
    title: "お問い合わせ",
    label: "CONTACT",
    icon: "",
    href: "/",
    show: true,
  },
];
